version: '3'
services:
  stock-monitor:
    image: stock-screener:v1
    container_name: stock_screen
    restart: unless-stopped
    volumes:
      - /data/stock/output:/app/data
    environment:
      - TZ=Asia/Shanghai